### ISSUE TITLE
Feature Request: the ability to use WIKI Code

### ISSUE THREAD

**Issue by LMS235** [cosmocode/csv#10]
It would be nice if i could use wiki code in the CSV file

- use of smileys (for example traffic light based on values)
- links
- text formatting

**Comment by splitbrain** [comment]
Sorry, not possible without introducing huge performance issues.

**Comment by jochenwezel** [comment]
I understand there might be a huge performance impact. Would it be an option to enable this feature by an additional attribute to the csv tag? Example:
```<csv apply=smileys,links,formattings>...</csv>```

If only links shall be detected and rendered as links, you could easily just enable this by
```<csv apply=links>...</csv>```
