### ISSUE TITLE
Google Docs Spreadsheet

### ISSUE THREAD

**Issue by marculius-67** [cosmocode/csv#22]
If I try to use a google spreadsheets link as such:
`<csv file="https://docs.google.com/spreadsheets/d/e/{PUBLISH_KEY}/pub?gid=0&single=true&output=csv" ></csv>`
I get "Failed to fetch remote CSV data"
If I try some other web address for example: 
`<csv file="https://raw.githubusercontent.com/cosmocode/csv/master/_test/csv/c-q-q-newlines_crlf.csv" ></csv>`
it works just fine.

I also tried:
`<csv file="https://docs.google.com/spreadsheets/d/{SHARE_LINK_KEY}/export?format=csv></csv>`
And it dose not work;
but this does:
`<csv file="https://docs.google.com/spreadsheets/d/{SHARE_LINK_KEY}/gviz/tq?tqx=out:csv" ></csv>`

A csv file hosted on google drive also works with:
`<csv file="https://drive.google.com/uc?export=download&id={LINK_KEY}" ></csv>`

Unfortunately the third "tq querry" is not a great solution as it returns empty cells where there is text in an otherwise numbers column; and it returns unnecessary empty columns if the cells are in some way formatted.

**Comment by tomabrafix** [comment]
This seems to be a problem in the HTTPClient of DokuWiki. Google Docs return the HTTP Status Code 307 but the DokuWiki HTTPClient can only handle 301 and 302.

**Comment by tomabrafix** [comment]
https://github.com/splitbrain/dokuwiki/pull/3515
