### ISSUE TITLE
Google Sheets : error message when "file=" attribute not mentioned

### ISSUE THREAD

**Issue by Patric77** [cosmocode/csv#25]
When displaying a Google Sheets worksheet, something's wrong in the plugin: it only works when you specify the optional "file" attribute.

Bug reported by Andi here :
https://forum.dokuwiki.org/d/19845-csv-plugin-with-google-sheets-document-failed-to-fetch-remote-csv-data-error/5

**Comment by splitbrain** [comment]
The problem is the equal signs in the URL. The options parser checks for equal signs before anything else, so `file` is mandatory in this case.
